# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedEmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(editable=False, max_length=254, verbose_name='Event')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('data', models.TextField(editable=False, verbose_name='Raw data for the event')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='email_tracker.EmailCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='esp_message_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, editable=False, verbose_name='ESP message ID'),
        ),
        migrations.AddField(
            model_name='trackedemailevent',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='email_tracker.TrackedEmail'),
        ),
    ]
